### ISSUE TITLE
Any updates on this?

### ISSUE THREAD

**Issue by firasuke** [void-linux/musl-obstack#3]
Hey there,

Are there any chances that you're going to keep this on par with the latest upstream version?

Thank you for your time and effort.

**Comment by ericonr** [comment]
Is it missing any functionality?

**Comment by firasuke** [comment]
No

**Comment by Vaelatern** [comment]
Then is there a purpose to the query?

**Comment by firasuke** [comment]
Is there a purpose not to kindly request a package be kept up-to-date with the upstream version?

**Comment by Vaelatern** [comment]
If there is a problem to be solved, like upstream having security patches we don't, or upstream having other benefits in their code we lack, then it would be worth the effort to make changes.

If you are offering to do some work to modernize, then it might be worth the effort to bring that work in to this tree.

If you are just chasing the "last commit" metric, and there seems to be no benefit other than that, I'd have to wonder why.

**Comment by firasuke** [comment]
I'm simply requesting this repository's maintainer to update its contents, and keep it on par with the latest upstream version nothing more, nothing less.

The repository maintainer has the right to accept or decline and close this issue.

**Comment by Vaelatern** [comment]
1) to what end?
2) Are you aware of any commits at all upstream?

**Comment by Vaelatern** [comment]
Are you promising work? Raising awareness of an issue? Do you think there are problems if you receive one answer instead of another answer?

**Comment by pullmoll** [comment]
https://github.com/void-linux/musl-obstack/releases/tag/v1.2

**Comment by firasuke** [comment]
Thanks for your time and effort!
