### ISSUE TITLE
Needs soname bump, broke ABI

### ISSUE THREAD

**Issue by ericonr** [void-linux/musl-obstack#4]
See https://github.com/void-linux/void-packages/issues/24792

Can confirm, `anacron` needs `obstack_free`, but new `libobstack.so.0` only offers `_obstack_free`.

@pullmoll

**Comment by pullmoll** [comment]
I **love** it... darn

**Comment by pullmoll** [comment]
https://github.com/void-linux/musl-obstack/commit/af9e73f7f200f8722c2b38c20ed23707d18f56e2

**Comment by ericonr** [comment]
Thanks!
